---
- hosts: all
  become: yes
  gather_facts: yes
- hosts: HAproxy
  become: yes
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: true
    - name: Install haproxy
      apt:
        name: haproxy
        state: present
    - name: Configure haproxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        
    - name: restart haproxy
      service:
        name: haproxy
        state: restarted
- hosts: webservers
  become: yes
  become_method: sudo
  tasks:
    - name: apt update
      apt:
        update_cache: true
    - name: Install Python,pip3,Flask and venv
      apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
    - name: Installing Gunicorn
      apt:
        name: gunicorn
    - name: Copy Flask app files
      copy:
        src: app.py
        dest: /home/ubuntu/app.py
    - name: Running Flask application
      shell: gunicorn -w 2 -D -b 0.0.0.0:8080 app:app
