Installs and configures haproxy on the haproxy host
- hosts: HAproxy
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Install haproxy
      apt:
        name: haproxy
        state: present

    - name: Configure haproxy
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
      become: true

- hosts: webservers
  become: yes
  tasks:
    - name: apt update
      apt:
        update_cache: yes

    - name: Install Python and Flask
      become: yes
      apt:
        name:
          - python3
          - python3-pip
        state: present
    - name: Intsall Flask
      apt:
        name: flask app
        state: present


    - name: Copy Flask app
      hosts: webservers
      become: true
  tasks:

    - name: Copy Flask app files
      copy:
        src: appA.py
        dest: /opt/appA.py
      notify:
        - start flask app
  handlers:
   - name: start flask app
     service:
      name: appA.py
      state: started
